plugins {
    id "java"
    id "maven-publish"
}

repositories {
    mavenCentral()
}

static def getOSName() {
    final String osName = System.getProperty("os.name").toLowerCase()
    if (osName.contains("linux")) {
        return ("linux")
    } else if (osName.contains("mac os x") || osName.contains("darwin") || osName.contains("osx")) {
        return ("mac")
    } else if (osName.contains("windows")) {
        return ("win")
    }
    return ""
}

ext {
    def buildTimeAndDate = new Date()
    buildDate = buildTimeAndDate.format("yyyy-MM-dd")
    buildTime = buildTimeAndDate.format("HH:mm:ss.SSSZ")

    javaVersion = System.properties["java.version"]
    javaVendor = System.properties["java.vendor"]
    javaVmVersion = System.properties["java.vm.version"]
    platform = getOSName()
}

// java language level.
sourceCompatibility = "25"
targetCompatibility = "25"

dependencies {
    implementation "org.openjfx:javafx-base:25.0.3:${platform}"
    implementation "org.openjfx:javafx-graphics:25.0.3:${platform}"
}

// configure publish tasks.
apply from: rootProject.file("gradle/publish-pom.gradle")

// task to create jar with source code.
task("sourceJar", type: Jar) {
    group = "Build"
    description = "An archive of the source code"
    archiveClassifier = "sources"
    from sourceSets.main.allJava
}

// task to create jar with javadocs.
task("javadocJar", type: Jar) {
    group = "Build"
    description = "An archive of the javadoc"
    archiveClassifier = "javadoc"
    from javadoc
}

jar.finalizedBy generatePomFileForMavenPublication
jar.finalizedBy sourceJar
jar.finalizedBy javadocJar

artifacts {
    archives jar
    archives sourceJar
    archives javadocJar
    generatePomFileForMavenPublication
}

compileJava {
    javadoc {
        options.addStringOption("Xdoclint:none", "-quiet")
    }
}

jar {
    manifest.attributes(
        "Created-By": project.javaVersion +
            " (" + project.javaVendor + " " + project.javaVmVersion + ")",
        "Build-Date": project.buildDate,
        "Build-Time": project.buildTime,
        "Specification-Title": project.name,
        "Specification-Version": project.version,
        "Specification-Vendor": project.vendor,
        "Implementation-Title": project.name,
        "Implementation-Version": project.version,
        "Implementation-Vendor": project.vendor,
        "Automatic-Module-Name": "org.testfx.monocle",
    )
}
